export const AMERICA_TIMEZONES = [
    { "country": "Argentina", "iso2": "AR", "default": "America/Argentina/Buenos_Aires", "timezones": ["America/Argentina/Buenos_Aires"] },
    { "country": "Bolivia", "iso2": "BO", "default": "America/La_Paz", "timezones": ["America/La_Paz"] },
    { "country": "Brazil", "iso2": "BR", "default": "America/Sao_Paulo", "timezones": ["America/Noronha", "America/Sao_Paulo", "America/Manaus", "America/Cuiaba", "America/Porto_Velho", "America/Boa_Vista", "America/Rio_Branco", "America/Eirunepe", "America/Fortaleza", "America/Recife", "America/Belem"] },
    { "country": "Canada", "iso2": "CA", "default": "America/Toronto", "timezones": ["America/St_Johns", "America/Halifax", "America/Moncton", "America/Toronto", "America/Winnipeg", "America/Regina", "America/Edmonton", "America/Vancouver", "America/Whitehorse", "America/Dawson"] },
    { "country": "Chile", "iso2": "CL", "default": "America/Santiago", "timezones": ["America/Santiago", "America/Punta_Arenas", "Pacific/Easter"] },
    { "country": "Colombia", "iso2": "CO", "default": "America/Bogota", "timezones": ["America/Bogota"] },
    { "country": "Costa Rica", "iso2": "CR", "default": "America/Costa_Rica", "timezones": ["America/Costa_Rica"] },
    { "country": "Cuba", "iso2": "CU", "default": "America/Havana", "timezones": ["America/Havana"] },
    { "country": "Dominican Republic", "iso2": "DO", "default": "America/Santo_Domingo", "timezones": ["America/Santo_Domingo"] },
    { "country": "Ecuador", "iso2": "EC", "default": "America/Guayaquil", "timezones": ["America/Guayaquil", "Pacific/Galapagos"] },
    { "country": "El Salvador", "iso2": "SV", "default": "America/El_Salvador", "timezones": ["America/El_Salvador"] },
    { "country": "Guatemala", "iso2": "GT", "default": "America/Guatemala", "timezones": ["America/Guatemala"] },
    { "country": "Haiti", "iso2": "HT", "default": "America/Port-au-Prince", "timezones": ["America/Port-au-Prince"] },
    { "country": "Honduras", "iso2": "HN", "default": "America/Tegucigalpa", "timezones": ["America/Tegucigalpa"] },
    { "country": "Jamaica", "iso2": "JM", "default": "America/Jamaica", "timezones": ["America/Jamaica"] },
    { "country": "Mexico", "iso2": "MX", "default": "America/Mexico_City", "timezones": ["America/Tijuana", "America/Hermosillo", "America/Chihuahua", "America/Mazatlan", "America/Monterrey", "America/Mexico_City", "America/Merida", "America/Cancun"] },
    { "country": "Nicaragua", "iso2": "NI", "default": "America/Managua", "timezones": ["America/Managua"] },
    { "country": "Panama", "iso2": "PA", "default": "America/Panama", "timezones": ["America/Panama"] },
    { "country": "Paraguay", "iso2": "PY", "default": "America/Asuncion", "timezones": ["America/Asuncion"] },
    { "country": "Peru", "iso2": "PE", "default": "America/Lima", "timezones": ["America/Lima"] },
    { "country": "Puerto Rico", "iso2": "PR", "default": "America/Puerto_Rico", "timezones": ["America/Puerto_Rico"] },
    { "country": "United States", "iso2": "US", "default": "America/New_York", "timezones": ["America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles", "America/Phoenix", "America/Anchorage", "Pacific/Honolulu"] },
    { "country": "Uruguay", "iso2": "UY", "default": "America/Montevideo", "timezones": ["America/Montevideo"] },
    { "country": "Venezuela", "iso2": "VE", "default": "America/Caracas", "timezones": ["America/Caracas"] },
    { "country": "Belize", "iso2": "BZ", "default": "America/Belize", "timezones": ["America/Belize"] },
    { "country": "Bahamas", "iso2": "BS", "default": "America/Nassau", "timezones": ["America/Nassau"] },
    { "country": "Barbados", "iso2": "BB", "default": "America/Barbados", "timezones": ["America/Barbados"] },
    { "country": "Bermuda", "iso2": "BM", "default": "Atlantic/Bermuda", "timezones": ["Atlantic/Bermuda"] },
    { "country": "Trinidad and Tobago", "iso2": "TT", "default": "America/Port_of_Spain", "timezones": ["America/Port_of_Spain"] },
    { "country": "Guyana", "iso2": "GY", "default": "America/Guyana", "timezones": ["America/Guyana"] },
    { "country": "Suriname", "iso2": "SR", "default": "America/Paramaribo", "timezones": ["America/Paramaribo"] },
    { "country": "French Guiana", "iso2": "GF", "default": "America/Cayenne", "timezones": ["America/Cayenne"] },
    { "country": "Greenland", "iso2": "GL", "default": "America/Nuuk", "timezones": ["America/Nuuk", "America/Thule", "America/Scoresbysund", "America/Danmarkshavn"] }
]
