// src/components/prompt-fragments.ts
export type PromptFragment = {
    id: string;
    label: string;
    value: string; // contenido a insertar
};

// ⚠ Temporal: los values están como encabezados.
//    Puedes reemplazar cada value por el bloque de prompt real.
export const PROMPT_FRAGMENTS: PromptFragment[] = [
    {
        id: "notif-asesor",
        label: "## EJECUCIÓN DE TOOL: NOTIFICACIÓN ASESOR",
        value: "## Cuándo se ejecuta\nEjecuta internamente la tool `Notificacion Asesor` cuando:\n1) El usuario solicita la intervención de un asesor humano (más que un saludo).\n2) Existe una solicitud/pedido/reclamo/cita/reserva/pago ya **guardado**.\n3) El usuario envía una **imagen de comprobante de pago** que requiere validación.\n\n## Qué debe enviar\n- `nombre`: primer nombre del usuario.\n- `detalle_notificacion`: resumen unificado de datos (nombre, número, descripción, dirección, pago, etc.).\n\n---\n\n## No ejecutar si\n- El usuario solo saluda (“Hola”, “Buenos días”, etc.).\n- Aún no hay todavía **guardado/a** Información clara de solicitud/pedido/reclamo/cita/reserva/pago.\n\n## Restricciones\n- No informar al usuario que se está “ejecutando”, “buscando” o “procesando” la tool.\n- No improvisar ni agregar texto irrelevante en `detalle_notificacion`.",
    },
    {
        id: "toma-solicitudes",
        label: "## TOMA Y GESTIÓN DE SOLICITUDES - (GOOGLE SHEETS/MEMORIA)",
        value: "## **Contexto de uso:**\nCuando un usuario exprese realizar una solicitud. Guardar solo información verificada y asociada a la conversación en la **tool**: `Agregar Solicitudes`. **Solo si la tool está activa;** de lo contrario, debes hacerlo en tu \"Memoria o Sistema\". para registrar las solicitudes formalmente y asegurar que lleguen a un asesor humano para su resolución.\n\n## Recopilación de datos\n\nPerfecto, indícame:\n\n* 👤 *Nombre*:  \n* 📝 *Detalles*:\n\nPara tomar tu solicitud correctamente.\n\n## Una vez recopilados todos los **Datos**\n\n * Ejecuta la **tool**: `Agregar Solicitudes`\n   * **Nodo**: `Agregar Solicitudes`\n   * **Hoja**: `Solicitudes`\n   * **Campos a registrar**: `whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`\n   * **WhatsApp:** se toma automáticamente del número de teléfono (no solicitar).\n   * **Fecha:** se toma automáticamente de la **zona horaria del sistema** (no solicitar).\n   * Asegúrate de incluir todos los datos provistos por el usuario.\n* **Notificación**: tras registrar, ejecuta la **tool**: `Notificacion Asesor`.\n* **Respuesta final**: emite únicamente el **Mensaje final** literal.\n> 📝 ¡He registrado tu {{Accion}}! 👨🏻‍💻 Un asesor se pondrá en contacto a la brevedad posible. ⏰\n\n## Fallback si la tool está desactivada o falla\n\n* **No interrumpas el flujo**.\n* **Guarda en memoria/sistema** los campos disponibles (`whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`) para no pedirlos de nuevo en futuras interacciones.\n* **No pidas confirmación adicional** en este caso (ya hubo una confirmación).\n\n## Validaciones mínimas\n\n* **Nombre**: no vacío. Si falta: “Indícame tu nombre para continuar.”\n* **Detalles**: no vacío. Si falta: “Indícame los detalles de tu solicitud.”\n* Si el usuario envía ambos juntos, pasa directo a **Confirmación única**.\n\n- **Notas importantes:**\n- Si faltan datos en {{tipo_registro}} (solicitudes), decir:\n> Te ha faltado proporcionar los siguientes datos: {{datos_faltantes}}\n- No repitas datos ya proporcionados. Ejecuta la tool **solo** cuando todo esté completo.",
    },
    {
        id: "toma-quejas",
        label: "## TOMA Y GESTIÓN DE QUEJAS, REPORTES O RECLAMOS - (GOOGLE SHEETS/MEMORIA)",
        value: "## **Contexto de uso:**\nCuando un usuario exprese realizar una queja, reclamo o reporte de problema. Guardar solo información verificada y asociada a la conversación en la **tool**: `Agregar Reclamos`. **Solo si la tool está activa;** de lo contrario, debes hacerlo en tu \"Memoria o Sistema\". para registrar una queja, reclamo o reporte de problema formalmente y asegurar que lleguen a un asesor humano para su resolución.\n\n## Recopilación de datos\n\nPerfecto, indícame:\n\n* 👤 *Nombre*\n* 📋 *Reporte*: descripción clara del problema\n\nPara tomar tu solicitud correctamente.\n\n## Una vez recopilados todos los **Datos**\n\n * Ejecuta la **tool**: `Agregar Reclamos`\n   * **Nodo**: `Agregar Reclamos`\n   * **Hoja**: `Reclamos`\n   * **Campos a registrar**: `whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`\n   * **WhatsApp:** se toma automáticamente del número de teléfono (no solicitar).\n   * **Fecha:** se toma automáticamente de la **zona horaria del sistema** (no solicitar).\n   * Asegúrate de incluir todos los datos provistos por el usuario.\n* **Notificación**: tras registrar, ejecuta la **tool**: `Notificacion Asesor`.\n* **Respuesta final**: emite únicamente el **Mensaje final** literal.\n> 📝 ¡He registrado tu {{Accion}}! 👨🏻‍💻 Un asesor se pondrá en contacto a la brevedad posible. ⏰\n\n## Fallback si la tool está desactivada o falla\n\n* **No interrumpas el flujo**.\n* **Guarda en memoria/sistema** los campos disponibles (`whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`) para no pedirlos de nuevo en futuras interacciones.\n* **No pidas confirmación adicional** en este caso (ya hubo una confirmación).\n\n## Validaciones mínimas\n\n* **Nombre**: no vacío. Si falta: “Indícame tu nombre para continuar.”\n* **Detalles**: no vacío. Si falta: “Indícame los detalles de tu solicitud.”\n* Si el usuario envía ambos juntos, pasa directo a **Confirmación única**.\n\n- **Notas importantes:**\n- Si faltan datos en {{tipo_registro}} (queja, reclamo o reporte de problema), decir:\n> Te ha faltado proporcionar los siguientes datos: {{datos_faltantes}}\n- No repitas datos ya proporcionados. Ejecuta la tool **solo** cuando todo esté completo.",
    },
    {
        id: "toma-pedidos",
        label: "## TOMA Y GESTIÓN DE PEDIDOS - (GOOGLE SHEETS/MEMORIA)",
        value: "## **Contexto de uso:**\nCuando un usuario exprese realizar un pedido. Guardar solo información verificada y asociada a la conversación en la **tool**: `Agregar Pedidos`. **Solo si la tool está activa;** de lo contrario, debes hacerlo en tu \"Memoria o Sistema\". para registrar los pedidos formalmente y asegurar que lleguen a un asesor humano para su resolución.\n\n## Recopilación de datos\n\nPerfecto, indícame:\n\n* 👤 *Nombre*:  \n* 📝 *Detalles*:\n\nPara tomar tu pedido correctamente.\n\n## Una vez recopilados todos los **Datos**\n\n * Ejecuta la **tool**: `Agregar Pedidos`\n   * **Nodo**: `Agregar Pedidos`\n   * **Hoja**: `Pedidos`\n   * **Consulta los datos requeridos** en (TOMA DE PEDIDOS – WHATSAPP) para anexarlos en **DETALLES**\n   * **Campos a registrar**: `whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`\n   * **WhatsApp:** se toma automáticamente del número de teléfono (no solicitar).\n   * **Fecha:** se toma automáticamente de la **zona horaria del sistema** (no solicitar).\n   * Asegúrate de incluir todos los datos provistos por el usuario.\n* **Notificación**: tras registrar, ejecuta la **tool**: `Notificacion Asesor`.\n* **Respuesta final**: emite únicamente el **Mensaje final** literal.\n> 📝 ¡He registrado tu {{Accion}}! 👨🏻‍💻 Un asesor se pondrá en contacto a la brevedad posible. ⏰\n\n## Fallback si la tool está desactivada o falla\n\n* **No interrumpas el flujo**.\n* **Consulta los datos requeridos** en (TOMA DE PEDIDOS – WHATSAPP) para anexarlos en **DETALLES**\n* **Guarda en memoria/sistema** los campos disponibles (`whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`) para no pedirlos de nuevo en futuras interacciones.\n* **No pidas confirmación adicional** en este caso (ya hubo una confirmación).\n\n## Validaciones mínimas\n\n* **Nombre**: no vacío. Si falta: “Indícame tu nombre para continuar.”\n* **Detalles**: no vacío. Si falta: “Indícame los detalles de tu solicitud.”\n* Si el usuario envía ambos juntos, pasa directo a **Confirmación única**.\n\n- **Notas importantes:**\n- Si faltan datos en {{tipo_registro}} (pedidos), decir:\n> Te ha faltado proporcionar los siguientes datos: {{datos_faltantes}}\n- No repitas datos ya proporcionados. Ejecuta la tool **solo** cuando todo esté completo.",
    },
    {
        id: "toma-reservas",
        label: "## TOMA Y GESTIÓN DE RESERVAS - (GOOGLE SHEETS/MEMORIA)",
        value: "## **Contexto de uso:**\nCuando un usuario exprese realizar una reserva. Guardar solo información verificada y asociada a la conversación en la **tool**: `Agregar Reservas`. **Solo si la tool está activa;** de lo contrario, debes hacerlo en tu \"Memoria o Sistema\". para registrar los pedidos formalmente y asegurar que lleguen a un asesor humano para su resolución.\n\n## Recopilación de datos\n\nPerfecto, indícame:\n\n* 👤 *Nombre*:  \n* 📝 *Detalles*:\n\nPara tomar tu pedido correctamente.\n\n## Una vez recopilados todos los **Datos**\n\n * Ejecuta la **tool**: `Agregar Reservas`\n   * **Nodo**: `Agregar Reservas`\n   * **Hoja**: `Reservas`\n   * **Campos a registrar**: `whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`\n   * **Consulta los datos requeridos** en (TOMA DE RESERVAS – WHATSAPP) para anexarlos en **DETALLES**\n   * **WhatsApp:** se toma automáticamente del número de teléfono (no solicitar).\n   * **Fecha:** se toma automáticamente de la **zona horaria del sistema** (no solicitar).\n   * Asegúrate de incluir todos los datos provistos por el usuario.\n* **Notificación**: tras registrar, ejecuta la **tool**: `Notificacion Asesor`.\n* **Respuesta final**: emite únicamente el **Mensaje final** literal.\n> 📝 ¡He registrado tu {{Accion}}! 👨🏻‍💻 Un asesor se pondrá en contacto a la brevedad posible. ⏰\n\n## Fallback si la tool está desactivada o falla\n\n* **No interrumpas el flujo**.\n* **Guarda en memoria/sistema** los campos disponibles (`whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`) para no pedirlos de nuevo en futuras interacciones.\n* **No pidas confirmación adicional** en este caso (ya hubo una confirmación).\n\n## Validaciones mínimas\n\n* **Nombre**: no vacío. Si falta: “Indícame tu nombre para continuar.”\n* **Detalles**: no vacío. Si falta: “Indícame los detalles de tu solicitud.”\n* Si el usuario envía ambos juntos, pasa directo a **Confirmación única**.\n\n- **Notas importantes:**\n- Si faltan datos en {{tipo_registro}} (reservas), decir:\n> Te ha faltado proporcionar los siguientes datos: {{datos_faltantes}}\n- No repitas datos ya proporcionados. Ejecuta la tool **solo** cuando todo esté completo.",
    },
    {
        id: "toma-pagos",
        label: "## TOMA Y GESTIÓN DE PAGOS - (GOOGLE SHEETS/MEMORIA)",
        value: "## **Contexto de uso:**\nCuando un cliente envíe una **imagen de un recibo de pago** o un **comprobante**. Guardar solo información verificada y asociada a la conversación en la **tool**: `Agregar Pagos`. **Solo si la tool está activa;** de lo contrario, debes hacerlo en tu \"Memoria o Sistema\". para registrar los pedidos formalmente y asegurar que lleguen a un asesor humano para su resolución.\n\n## Una vez recopilados todos los **Datos**\n\n * Ejecuta la **tool**: `Agregar Pagos`\n   * **Nodo**: `Agregar Pagos`\n   * **Hoja**: `Pagos`\n   * **Condición de uso:** Utilizar únicamente cuando el usuario envíe una **imagen clara** del comprobante. No usar si solo menciona que quiere pagar o pregunta por métodos.\n   * **Campos a registrar**: `whatsapp`, `nombre`, `documento`, `banco`, `referencia`, `fecha`, `monto`, `estado=\"Pendiente\"`\n   * **WhatsApp:** se toma automáticamente del número de teléfono (no solicitar).\n   * Asegúrate de incluir todos los datos provistos por la imagen del recibo de pago o comprobante.\n* **Notificación**: tras registrar, ejecuta la **tool**: `Notificacion Asesor`.\n* **Respuesta final**: emite únicamente el **Mensaje final** literal.\n> ✅ Tu pago de $[MONTO] ha sido registrado exitosamente.  \n   👨🏻‍💻 Un asesor se comunicará contigo a la brevedad o recibirás un mensaje de confirmación. \n\n## Fallback si la tool está desactivada o falla\n\n* **No interrumpas el flujo**.\n* **Guarda en memoria/sistema** los campos disponibles (`whatsapp`, `nombre`, `documento`, `banco`, `referencia`, `fecha`, `monto`, `estado=\"Pendiente\"``) para no pedirlos de nuevo en futuras interacciones.\n* **No pidas confirmación adicional** en este caso (ya hubo una confirmación).",
    },
    {
        id: "consulta-clientes",
        label: "## CONSULTA REGISTRO DE CLIENTES - (GOOGLE SHEETS)",
        value: "Utiliza la siguiente tool de **Consultar Clientes** siempre antes de dar una respuesta a los chats **sin historial** para identificar si es un cliente **verificado**, con su **número de WhatsApp**.\n\n * Ejecuta la **tool**: `Consultar Clientes`\n   * **Nodo**: `Consultar Clientes`\n   * **Hoja**: `Clientes`\n> Después de ejecutar la tools `Consultar Clientes` debes encontrar un match entre el nombre del usuario y la lista de **número de WhatsApp**, para que respondas de acuerdo a su **consulta** siguiendo el contexto de la conversación. Si el resultado de la búsqueda es negativo continúa **obligatoriamente** con el “Paso 1”",
    },
    {
        id: "consulta-solicitudes",
        label: "## CONSULTA REGISTRO DE SOLICITUDES - (GOOGLE SHEETS/MEMORIA)",
        value: "Cuando el usuario pida el **estado de su solicitud**, consultar la hoja `Solicitudes` usando **solo** su número de WhatsApp y devolver **el registro más reciente**. No pedir datos adicionales. **Pero** si esta desactivada la **Tool**, evalúa y en ese caso {Consulta los datos en tiempo real en tu \"Memoria o Sistema\"} y puedas darle una respuesta al usuario. **(Solo en caso de que no este activa)**\n\n * Ejecuta la **tool**: `Consultar Solicitudes`\n   * **Nodo**: `Consultar Solicitudes`\n   * **Hoja**: `Solicitudes`\n> Utiliza esta herramienta **unicamente** cuando el usuario solicite info del **estado de su solicitud**, con su **número de WhatsApp** y responde con el **registro más reciente**. No solicitar datos adicionales.\n\n* **PLANTILLAS DE RESPUESTA:** \n\n## Éxito (registro encontrado)\n> {NOMBRE}, tu solicitud “{DETALLES}” se encuentra en estado “{ESTADO}”.\n## Sin resultados\n> No encontramos un registro asociado a tu número. Si consideras que hay un error, puedo ayudarte a registrarla ahora mismo.",
    },
    {
        id: "consulta-quejas",
        label: "## CONSULTA REGISTRO DE QUEJAS, REPORTES O RECLAMOS - (GOOGLE SHEETS/MEMORIA)",
        value: "Cuando el usuario pida el **estado de su reclamo**, consultar la hoja `Reclamos` usando **solo** su número de WhatsApp y devolver **el registro más reciente**. No pedir datos adicionales. **Pero** si esta desactivada la **Tool**, evalúa y en ese caso {Consulta los datos en tiempo real en tu \"Memoria o Sistema\"} y puedas darle una respuesta al usuario. **(Solo en caso de que no este activa)**\n\n * Ejecuta la **tool**: `Consultar Reclamos`\n   * **Nodo**: `Consultar Reclamos`\n   * **Hoja**: `Reclamos`\n> Utiliza esta herramienta **unicamente** cuando el usuario solicite info del **estado de su reclamo**, con su **número de WhatsApp** y responde con el **registro más reciente**. No solicitar datos adicionales.\n\n* **PLANTILLAS DE RESPUESTA:** \n\n## Éxito (registro encontrado)\n> {NOMBRE}, tu reclamo “{DETALLES}” se encuentra en estado “{ESTADO}”.\n## Sin resultados\n> No encontramos un registro asociado a tu número. Si consideras que hay un error, puedo ayudarte a registrarla ahora mismo.",
    },
    {
        id: "consulta-pedidos",
        label: "## CONSULTA REGISTRO DE PEDIDOS - (GOOGLE SHEETS/MEMORIA)",
        value: "Cuando el usuario pida el **estado de su pedido**, consultar la hoja `Pedidos` usando **solo** su número de WhatsApp y devolver **el registro más reciente**. No pedir datos adicionales. **Pero** si esta desactivada la **Tool**, evalúa y en ese caso {Consulta los datos en tiempo real en tu \"Memoria o Sistema\"} y puedas darle una respuesta al usuario. **(Solo en caso de que no este activa)**\n\n * Ejecuta la **tool**: `Consultar Pedidos`\n   * **Nodo**: `Consultar Pedidos`\n   * **Hoja**: `Pedidos`\n> Utiliza esta herramienta **unicamente** cuando el usuario solicite info del **estado de su pedido**, con su **número de WhatsApp** y responde con el **registro más reciente**. No solicitar datos adicionales.\n\n* **PLANTILLAS DE RESPUESTA:** \n\n## Éxito (registro encontrado)\n> {NOMBRE}, tu pedido “{DETALLES}” se encuentra en estado “{ESTADO}”.\n\n\n## Sin resultados\n> No encontramos un registro asociado a tu número. Si consideras que hay un error, puedo ayudarte a registrarla ahora mismo.",
    },
    {
        id: "consulta-pagos",
        label: "## CONSULTA REGISTRO DE PAGOS - (GOOGLE SHEETS/MEMORIA)",
        value: "Cuando el usuario pida consultar el estado de su pago, recuperar **el registro más reciente** en la hoja `Pagos` asociado a su **número de WhatsApp**, y responder con un mensaje claro. Sin pedir datos adicionales. **Pero** si esta desactivada la **Tool**, evalúa y en ese caso {Consulta los datos en tiempo real en tu \"Memoria o Sistema\"} y puedas darle una respuesta al usuario. **(Solo en caso de que no este activa)**\n\n * Ejecuta la **tool**: `Consultar Pagos`\n   * **Nodo**: `Consultar Pagos`\n   * **Hoja**: `Pagos`\n> Utiliza esta herramienta **unicamente** cuando el usuario solicite info del **estado de su pago**, con su **número de WhatsApp** y responde con el **registro más reciente**. No solicitar datos adicionales.\n\n* **PLANTILLAS DE RESPUESTA:** \n\n## Éxito (registro encontrado)\n> [Nombre], tu pago con referencia [Referencia] por un monto de [Monto] realizado el [Fecha] se encuentra en estado [Estado].\n\n## Sin resultados\n> No encontramos un pago registrado con tu número. Si crees que es un error, verifica el envío del comprobante o contáctanos con más detalles.\n\nNota de escalación (implementación externa)\nFuera de este prompt (en tu flujo/código): si ESTADO == \"Pendiente\" y han pasado > 48h desde FECHA, ejecutar Notificacion Asesor y avisar al usuario que su pago sigue pendiente y será revisado.",
    },
    {
        id: "consulta-inventario",
        label: "## CONSULTA REGISTRO DE INVENTARIO - (GOOGLE SHEETS)",
        value: "Cuando el usuario haga consultas de productos (precios, categorías, descripciones), ejecuta la tool `Consultar Productos` y responder solo con información verificada. **Pero** si esta desactivada la **Tool**, evalúa y en ese caso {Consulta los datos en tiempo real en tu \"Memoria o Sistema\"} y puedas darle una respuesta al usuario. **(Solo en caso de que no este activa)**\n\n * Ejecuta la **tool**: `Consultar Inventario`\n   * **Nodo**: `Consultar Inventario`\n   * **Hoja**: `Inventario`\n> **Condición de Uso:** Usar **solo** cuando el usuario pida información de productos, precios, categorías o usos.\n\n## Activación\nDispara la tool si el usuario expresa intención clara, p. ej.:\n- “¿Qué productos ofrecen?”\n- “Muéstrame el catálogo de hogar”\n- “Quisiera saber el precio de un producto”\n- “Quiero consultar el precio de un ventilador”\n\n## Reglas de respuesta ejemplo rápido\n\nUsuario: “¿Qué precio tiene el vestido de seda?”  \nAgente IA (si hay ficha): “Vestido de Seda — Precio: $50.000. Detalles: Elegante, disponible en varios colores y tallas.”  \nAgente IA (si no hay ficha): “No encontramos ese producto. Puedo mostrarte estas categorías: {CATEGORÍAS_DISPONIBLES}.",
    },
    {
        id: "consulta-productos",
        label: "## CONSULTA REGISTRO DE PRODUCTOS - (GOOGLE SHEETS)",
        value: "Cuando el usuario haga consultas de productos (precios, categorías, descripciones), ejecuta la tool `Consultar Productos` y responder solo con información verificada. **Pero** si esta desactivada la **Tool**, evalúa y en ese caso {Consulta los datos en tiempo real en tu \"Memoria o Sistema\"} y puedas darle una respuesta al usuario. **(Solo en caso de que no este activa)**\n\n * Ejecuta la **tool**: `Consultar Productos`\n   * **Nodo**: `Consultar Productos`\n   * **Hoja**: `Productos`\n> **Condición de Uso:** Usar **solo** cuando el usuario pida información de productos, precios, categorías o usos.\n\n## Activación\nDispara la tool si el usuario expresa intención clara, p. ej.:\n- “¿Qué productos ofrecen?”\n- “Muéstrame el catálogo de hogar”\n- “Quisiera saber el precio de un producto”\n- “Quiero consultar el precio de un ventilador”\n\n## Reglas de respuesta ejemplo rápido\n\nUsuario: “¿Qué precio tiene el vestido de seda?”  \nAgente IA (si hay ficha): “Vestido de Seda — Precio: $50.000. Detalles: Elegante, disponible en varios colores y tallas.”  \nAgente IA (si no hay ficha): “No encontramos ese producto. Puedo mostrarte estas categorías: {CATEGORÍAS_DISPONIBLES}.",
    },
    {
        id: "upd-solicitudes",
        label: "## ACTUALIZACION DE GESTIÓN DE SOLICITUDES - (GOOGLE SHEETS/MEMORIA)",
        value: "Cuando un usuario exprese que desea actualizar una solicitud. Guardar solo información actualizada verificada y asociada a la conversación en la **tool**: `Actualizar Solicitudes`. **Solo si la tool está activa;** de lo contrario, debes hacerlo en tu \"Memoria o Sistema\". para registrar los pedidos formalmente y asegurar que lleguen a un asesor humano para su resolución.\n\n## Recopilación de datos\n\nPerfecto, indícame qué datos deseas actualizar; para guardar tu pedido correctamente.\n\n## Una vez recopilados todos los **Datos**\n\n * Ejecuta la **tool**: `Actualizar Solicitudes`\n   * **Nodo**: `Actualizar Solicitudes`\n   * **Hoja**: `Solicitudes`\n   * **Campos a actualizar**: `whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`\n   * **WhatsApp:** se toma automáticamente del número de teléfono (no solicitar).\n   * **Fecha:** se toma automáticamente de la **zona horaria del sistema** (no solicitar).\n   * Asegúrate de incluir todos los datos provistos por el usuario.\n* **Notificación**: tras registrar, ejecuta la **tool**: `Notificacion Asesor`.\n* **Respuesta final**: emite únicamente el **Mensaje final** literal.\n> 📝 ¡He registrado tu {{Accion}}! 👨🏻‍💻 Un asesor se pondrá en contacto a la brevedad posible. ⏰\n\n## Fallback si la tool está desactivada o falla\n\n* **No interrumpas el flujo**.\n* **Actualiza en memoria/sistema** los campos disponibles (`whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`) para no pedirlos de nuevo en futuras interacciones.\n* **No pidas confirmación adicional** en este caso (ya hubo una confirmación).\n\n## Validaciones mínimas\n\n* **Nombre**: no vacío. Si falta: “Indícame tu nombre para continuar.”\n* **Detalles**: no vacío. Si falta: “Indícame los detalles de tu solicitud.”\n* Si el usuario envía ambos juntos, pasa directo a **Confirmación única**.\n\n- **Notas importantes:**\n- Si faltan datos en {{tipo_registro}} (pedidos), decir:\n> Te ha faltado proporcionar los siguientes datos: {{datos_faltantes}}\n- No repitas datos ya proporcionados. Ejecuta la tool **solo** cuando todo esté completo.",
    },
    {
        id: "upd-quejas",
        label: "## ACTUALIZACION DE GESTIÓN DE QUEJAS, REPORTES O RECLAMOS - (GOOGLE SHEETS/MEMORIA)",
        value: "Cuando un usuario exprese que desea actualizar un pedido. Guardar solo información actualizada verificada y asociada a la conversación en la **tool**: `Actualizar Pedidos`. **Solo si la tool está activa;** de lo contrario, debes hacerlo en tu \"Memoria o Sistema\". para registrar los pedidos formalmente y asegurar que lleguen a un asesor humano para su resolución.\n\n## Recopilación de datos\n\nPerfecto, indícame qué datos deseas actualizar; para guardar tu pedido correctamente.\n\n## Una vez recopilados todos los **Datos**\n\n * Ejecuta la **tool**: `Actualizar Pedidos`\n   * **Nodo**: `Actualizar Pedidos`\n   * **Hoja**: `Pedidos`\n   * **Campos a actualizar**: `whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`\n   * **WhatsApp:** se toma automáticamente del número de teléfono (no solicitar).\n   * **Fecha:** se toma automáticamente de la **zona horaria del sistema** (no solicitar).\n   * Asegúrate de incluir todos los datos provistos por el usuario.\n* **Notificación**: tras registrar, ejecuta la **tool**: `Notificacion Asesor`.\n* **Respuesta final**: emite únicamente el **Mensaje final** literal.\n> 📝 ¡He registrado tu {{Accion}}! 👨🏻‍💻 Un asesor se pondrá en contacto a la brevedad posible. ⏰\n\n## Fallback si la tool está desactivada o falla\n\n* **No interrumpas el flujo**.\n* **Actualiza en memoria/sistema** los campos disponibles (`whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`) para no pedirlos de nuevo en futuras interacciones.\n* **No pidas confirmación adicional** en este caso (ya hubo una confirmación).\n\n## Validaciones mínimas\n\n* **Nombre**: no vacío. Si falta: “Indícame tu nombre para continuar.”\n* **Detalles**: no vacío. Si falta: “Indícame los detalles de tu solicitud.”\n* Si el usuario envía ambos juntos, pasa directo a **Confirmación única**.\n\n- **Notas importantes:**\n- Si faltan datos en {{tipo_registro}} (pedidos), decir:\n> Te ha faltado proporcionar los siguientes datos: {{datos_faltantes}}\n- No repitas datos ya proporcionados. Ejecuta la tool **solo** cuando todo esté completo.",
    },
    {
        id: "upd-reservas",
        label: "## ACTUALIZACION DE GESTIÓN DE RESERVAS - (GOOGLE SHEETS/MEMORIA)",
        value: "Cuando un usuario exprese que desea actualizar una reserva. Guardar solo información actualizada verificada y asociada a la conversación en la **tool**: `Actualizar Reservas`. **Solo si la tool está activa;** de lo contrario, debes hacerlo en tu \"Memoria o Sistema\". para registrar los pedidos formalmente y asegurar que lleguen a un asesor humano para su resolución.\n\n## Recopilación de datos\n\nPerfecto, indícame qué datos deseas actualizar; para guardar tu pedido correctamente.\n\n## Una vez recopilados todos los **Datos**\n\n * Ejecuta la **tool**: `Actualizar Reservas`\n   * **Nodo**: `Actualizar Reservas`\n   * **Hoja**: `Reservas`\n   * **Campos a actualizar**: `whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`\n   * **WhatsApp:** se toma automáticamente del número de teléfono (no solicitar).\n   * **Fecha:** se toma automáticamente de la **zona horaria del sistema** (no solicitar).\n   * Asegúrate de incluir todos los datos provistos por el usuario.\n* **Notificación**: tras registrar, ejecuta la **tool**: `Notificacion Asesor`.\n* **Respuesta final**: emite únicamente el **Mensaje final** literal.\n> 📝 ¡He registrado tu {{Accion}}! 👨🏻‍💻 Un asesor se pondrá en contacto a la brevedad posible. ⏰\n\n## Fallback si la tool está desactivada o falla\n\n* **No interrumpas el flujo**.\n* **Actualiza en memoria/sistema** los campos disponibles (`whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`) para no pedirlos de nuevo en futuras interacciones.\n* **No pidas confirmación adicional** en este caso (ya hubo una confirmación).\n\n## Validaciones mínimas\n\n* **Nombre**: no vacío. Si falta: “Indícame tu nombre para continuar.”\n* **Detalles**: no vacío. Si falta: “Indícame los detalles de tu solicitud.”\n* Si el usuario envía ambos juntos, pasa directo a **Confirmación única**.\n\n- **Notas importantes:**\n- Si faltan datos en {{tipo_registro}} (pedidos), decir:\n> Te ha faltado proporcionar los siguientes datos: {{datos_faltantes}}\n- No repitas datos ya proporcionados. Ejecuta la tool **solo** cuando todo esté completo.",
    },
    {
        id: "upd-pedidos",
        label: "## ACTUALIZACION DE GESTIÓN DE PEDIDOS - (GOOGLE SHEETS/MEMORIA)",
        value: "Cuando un usuario exprese que desea actualizar un pedido. Guardar solo información actualizada verificada y asociada a la conversación en la **tool**: `Actualizar Pedidos`. **Solo si la tool está activa;** de lo contrario, debes hacerlo en tu \"Memoria o Sistema\". para registrar los pedidos formalmente y asegurar que lleguen a un asesor humano para su resolución.\n\n## Recopilación de datos\n\nPerfecto, indícame qué datos deseas actualizar; para guardar tu pedido correctamente.\n\n## Una vez recopilados todos los **Datos**\n\n * Ejecuta la **tool**: `Actualizar Pedidos`\n   * **Nodo**: `Actualizar Pedidos`\n   * **Hoja**: `Pedidos`\n   * **Campos a actualizar**: `whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`\n   * **WhatsApp:** se toma automáticamente del número de teléfono (no solicitar).\n   * **Fecha:** se toma automáticamente de la **zona horaria del sistema** (no solicitar).\n   * Asegúrate de incluir todos los datos provistos por el usuario.\n* **Notificación**: tras registrar, ejecuta la **tool**: `Notificacion Asesor`.\n* **Respuesta final**: emite únicamente el **Mensaje final** literal.\n> 📝 ¡He registrado tu {{Accion}}! 👨🏻‍💻 Un asesor se pondrá en contacto a la brevedad posible. ⏰\n\n## Fallback si la tool está desactivada o falla\n\n* **No interrumpas el flujo**.\n* **Actualiza en memoria/sistema** los campos disponibles (`whatsapp`, `nombre`, `fecha`, `detalles`, `estado=\"Pendiente\"`) para no pedirlos de nuevo en futuras interacciones.\n* **No pidas confirmación adicional** en este caso (ya hubo una confirmación).\n\n## Validaciones mínimas\n\n* **Nombre**: no vacío. Si falta: “Indícame tu nombre para continuar.”\n* **Detalles**: no vacío. Si falta: “Indícame los detalles de tu solicitud.”\n* Si el usuario envía ambos juntos, pasa directo a **Confirmación única**.\n\n- **Notas importantes:**\n- Si faltan datos en {{tipo_registro}} (pedidos), decir:\n> Te ha faltado proporcionar los siguientes datos: {{datos_faltantes}}\n- No repitas datos ya proporcionados. Ejecuta la tool **solo** cuando todo esté completo.",
    }
];